baseURL: https://jeanmichelstaelens.netlify.app
languageCode: en-us
title: Portfolio website for Jean-Michel Staelens
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: |-
    #  I am a current MBA2024 student at LBS. Welcome to my portfolio website!
    title: Hi, my name is Jean-Michel!
  blog: {}
  contact:
    address:
      - city: London, AA1 2BB
        country: United Kingdom
        street: Abbey Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jstaelens.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 123-4567
        title: Phone
  custom_css: []
  custom_js: []
  description: I am a current MBA2024 student at LBS. Welcome to my portfolio website!
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/jmstaelens95
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jmstaelens
  image: '28'
  name: Jean-Michel Staelens
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Returns of financial stocks (DJIA)
        title: Risk return
        url: blogs/risk_return
      - image: Amsterdam.jpg
        subtitle: Website I created from scratch in HTML and CSS for my family business.
        title: Staelens.nl
        url: https://www.staelens.nl
      - image: kurhaus.jpg
        subtitle: Introduction to data manipulation
        title: Homework 1
        url: blogs/homework1.qmd
      - image: mondrian_composition.jpg
        subtitle: Nisl Sed Aliquam
        title: Homework 2
        url: blogs/homework2
      - image: Johannes_Vermeer.jpg
        subtitle: Introduction to web scraping
        title: Homework 3
        url: blogs/ipsum
      - image: Vincent_van_Gogh.jpg
        subtitle: Introduction to Machine Learning
        title: Homework 4
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Welcome to the website of Jean-Michel, an ambitious MBA2024 student at the prestigious London Business School. Hailing from the picturesque Netherlands, Jean-Michel brings a unique blend of international perspective and analytical prowess to the world of business. With a profound passion for data science, he strives to harness the power of analytics and data-driven decision making to empower organizations in making informed and strategic choices.

Jean-Michel's journey has been one of continuous learning and growth, culminating in his pursuit of an MBA at London Business School. Throughout his academic and professional endeavors, he has consistently demonstrated a deep understanding of the intricacies of data analysis, and an unwavering commitment to helping companies make better decisions.
\n\n
With an astute grasp of statistical methods, programming languages, and advanced analytics tools, Jean-Michel is well-equipped to navigate the ever-evolving landscape of data science for business. He firmly believes that leveraging data-driven insights holds the key to unlocking untapped opportunities, optimizing operations, and driving sustainable growth.
\n\r
By exploring this website, you will gain invaluable insights into his experiences, projects, and research endeavors in the realm of data science for business. Whether you are a fellow student, an aspiring data scientist, or a business professional seeking innovative solutions, Jean-Michel's website serves as a valuable resource to further your understanding and application of analytics in the corporate world.
\n\r
Join Jean-Michel on his quest to revolutionize decision making through the power of data and embark on a transformative journey that has the potential to reshape the future of businesses worldwide."
    title: AI generated introduction of myself
    url: blogs
